### ISSUE TITLE
Current account creation fee: NaN STEEM

### ISSUE THREAD

**Issue by noisy** [gpurgal/getonsteem#1]
Website do not show current price of an account:

![selection_390](https://user-images.githubusercontent.com/201263/37887022-8590c55e-30bf-11e8-9c16-44cac67dae5f.png)

FYI: it looks like api.steemit.com returns this information:

![selection_391](https://user-images.githubusercontent.com/201263/37887058-c6751700-30bf-11e8-9f82-9b2fea40e941.png)

So this is probably some error on you website.

**Comment by gpurgal** [comment]
Fixed in f8bf46c120472a609fd2b60a171e81aaa63ddd62
Looks like config key returned by API has changed.
STEEM**IT**_CREATE_ACCOUNT_WITH_STEEM_MODIFIER -> STEEM_CREATE_ACCOUNT_WITH_STEEM_MODIFIER
